# Generated by Django 2.2.12 on 2020-08-22 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_cv', '0007_auto_20200822_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='cvExtras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.BooleanField(default=False)),
                ('interests', models.BooleanField(default=False)),
                ('languages', models.BooleanField(default=False)),
                ('certifications', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
