# Generated by Django 2.2.12 on 2020-08-23 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_cv', '0011_cvcertification'),
    ]

    operations = [
        migrations.CreateModel(
            name='cvLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=150)),
                ('proficiency', models.CharField(choices=[('1', 'Elementary'), ('2', 'Limited Working'), ('3', 'Professional Working'), ('4', 'Full Professional'), ('5', 'Native/Bilingual')], default='1', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
