# Generated by Django 2.2.12 on 2020-08-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_cv', '0012_cvlanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cveducation',
            name='level_of_study',
            field=models.CharField(default='A Level', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cveducation',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
