# Generated by Django 2.2.13 on 2020-08-30 04:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_cv', '0016_auto_20200825_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvprofile',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.DeleteModel(
            name='CV',
        ),
    ]
