# Generated by Django 2.2.12 on 2020-08-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200813_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CV',
        ),
    ]
