# Generated by Django 2.2.12 on 2020-08-21 23:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(default="Silly billy didn't write anything here!"),
            preserve_default=False,
        ),
    ]
